#!/bin/bash
ACV="2.5.1"
ARC=".tar.bz2"
APN="glibc"
export ACV ARC APN
ACB=$APN-$ACV
export ACB
###################################
#
#      Embryo Toolchain
#
###################################
cd $LSB
$TC $LSR/$ACB$ARC
cd $ACB
$PTC $LSP/glibc-2.5.1-iconvconfig_trampoline-1.patch
$PTC $LSP/glibc-2.5.1-localedef_trampoline-1.patch
$PTC $LSP/glibc-2.5.1-pt_pax-1.patch
cp -v elf/rtld.c{,.orig}
sed 's@/etc/ld.so.preload@/tools&@' elf/rtld.c.orig > elf/rtld.c
mkdir -v ../glibc-build
cd ../glibc-build
../$ACB/configure --prefix=/tools \
    --with-binutils=/tools/bin --with-headers=/tools/include \
    --enable-kernel=2.6.0 --enable-bind-now --enable-add-ons \
    --without-gd --disable-profile --without-selinux
make
install -vd /tools/etc
touch /tools/etc/ld.so.conf
make install

mv -v /tools/bin/{ld,ld-old}
mv -v /tools/$(gcc -dumpmachine)/bin/{ld,ld-old}
mv -v /tools/bin/{ld-new,ld}
ln -sv /tools/bin/ld /tools/$(gcc -dumpmachine)/bin/ld

gcc -dumpspecs | sed 's@/lib/@/tools/lib/@g' \
    > `dirname $(gcc -print-libgcc-file-name)`/specs

GCC_INCLUDEDIR=`dirname $(gcc -print-libgcc-file-name)`/include &&
find ${GCC_INCLUDEDIR}/* -maxdepth 0 -xtype d -exec rm -rvf '{}' \; &&
rm -vf `grep -l "DO NOT EDIT THIS FILE" ${GCC_INCLUDEDIR}/*` &&
unset GCC_INCLUDEDIR

